"use client"
import { useEffect, useState } from "react"

type Person={id:string;name:string;designation:string}
type Account={id:string;name:string;cluster:string;am:string;designer:string;writer:string}
type Team={lead:Person;people:Person[]}
type Data={buLead:Person;designLead:Person;contentLead:Person;clusters:Person[];design:Team[];content:Team[];accounts:Account[]}
const p=(id:string,name:string,designation=""):Person=>({id,name,designation})
const seed:Data={
 buLead:p("bu-lead","Rohan Mehta","BU Lead – BU1"),
 designLead:p("design-lead","Chetan Vijayakumar","CD – Design"),
 contentLead:p("content-lead","Jenny","CD – Content"),
 clusters:[p("cl1","Aarti Sharma","Cluster Lead 1"),p("cl2","Vikram Rao","Cluster Lead 2"),p("cl3","Simran Kaur","Cluster Lead 3")],
 design:[{lead:p("dl1","Kiran","Design Lead 1"),people:[p("d1","Arjun","Sr. Graphic Designer"),p("d2","Ashish","Sr. Graphic Designer"),p("d3","Lekha","Sr. Graphic Designer"),p("d4","Niranjana","Jr. Graphic Designer"),p("d5","Anu Umesh","Graphic Designer")]},{lead:p("dl2","Hari","Design Lead 2"),people:[p("d6","Akshay","Sr. Graphic Designer"),p("d7","Nejith","Graphic Designer"),p("d8","Fadi","Jr. Graphic Designer"),p("d9","Chaitanya","Intern – Designer")]},{lead:p("dl3","Toms","Design Lead 3"),people:[p("d10","Sai","Sr. Graphic Designer"),p("d11","Aras","Sr. Graphic Designer"),p("d12","Dheeraj","Sr. Graphic Designer"),p("d13","Meghna","Sr. Graphic Designer"),p("d14","Abhinav","Graphic Designer"),p("d15","Govind","Graphic Designer")]}],
 content:[{lead:p("cl4","Lara","Content Lead 1"),people:[p("w1","Diya","Sr. Content Writer"),p("w2","Saika","Content Writer")]},{lead:p("cl5","Ashna","Content Lead 2"),people:[p("w3","Aahana","Sr. Content Writer"),p("w4","Rhea","Content Writer"),p("w5","Kartik","Jr. Content Writer")]},{lead:p("cl6","Disha","Content Lead 3"),people:[p("w6","Anthony","Content Writer"),p("w7","Abhishek","Jr. Content Writer")]}],
 accounts:[
 {id:"a1",name:"WNS",cluster:"Cluster 1",am:"Neeraj Kulkarni",designer:"Arjun",writer:"Diya"},{id:"a2",name:"CMS",cluster:"Cluster 1",am:"Pooja Iyer",designer:"Ashish",writer:"Saika"},{id:"a3",name:"Tata Comms",cluster:"Cluster 1",am:"Karan Malhotra",designer:"Lekha",writer:"Aahana"},{id:"a4",name:"HCL TECH",cluster:"Cluster 1",am:"Isha Menon",designer:"Kiran",writer:"Rhea"},{id:"a5",name:"SuperMicro",cluster:"Cluster 1",am:"Vikram Rao",designer:"Kunal Jain",writer:"Kartik"},{id:"a6",name:"Straive",cluster:"Cluster 2",am:"Aditya Singh",designer:"Akshay",writer:"Anthony"},{id:"a7",name:"SOLAR EDGE",cluster:"Cluster 2",am:"Meera Nair",designer:"Nejith",writer:"Abhishek"},{id:"a8",name:"Xerox",cluster:"Cluster 3",am:"Arjun Desai",designer:"Sai",writer:"Disha"}
 ]}
const STORAGE="zen-bu1-pilot-v1"
function Card({person,onEdit}:{person:Person;onEdit:(p:Person)=>void}){return <button className="card" onClick={()=>onEdit(person)}><strong>{person.name}</strong>{person.designation&&<span>{person.designation}</span>}</button>}
function Add({label,onClick}:{label:string;onClick:()=>void}){return <button className="add" onClick={onClick}>+ {label}</button>}
export default function Home(){
 const [data,setData]=useState<Data>(seed);const [selected,setSelected]=useState<Person|null>(null);const [account,setAccount]=useState<Account|null>(null)
 useEffect(()=>{const raw=localStorage.getItem(STORAGE);if(raw)try{setData(JSON.parse(raw))}catch{}},[]);useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify(data))},[data])
 const edit=(p:Person)=>setSelected({...p});const save=()=>{if(!selected)return;const replace=(p:Person)=>p.id===selected.id?selected:p;setData(d=>({...d,buLead:replace(d.buLead),designLead:replace(d.designLead),contentLead:replace(d.contentLead),clusters:d.clusters.map(replace),design:d.design.map(t=>({...t,lead:replace(t.lead),people:t.people.map(replace)})),content:d.content.map(t=>({...t,lead:replace(t.lead),people:t.people.map(replace)}))}));setSelected(null)}
 const add=(kind:string)=>setData(d=>({...d,accounts:kind?d.accounts: d.accounts}));
 const updateAccount=(field:keyof Account,value:string)=>{if(!account)return;setData(d=>({...d,accounts:d.accounts.map(a=>a.id===account.id?{...a,[field]:value}:a)}));setAccount(a=>a?{...a,[field]:value}:a)}
 return <main><header><div><h1>Zen-Sheet · BU1 Pilot</h1><p>Editable people, account names and account-level coverage mapping</p></div><button className="reset" onClick={()=>{localStorage.removeItem(STORAGE);location.reload()}}>Reset</button></header>
 <section className="canvas"><div className="pilot">
  <div className="pilotTop"><Card person={data.buLead} onEdit={edit}/></div><div className="pilotBranches"><section><Card person={data.buLead} onEdit={edit}/><h3>Cluster Leads / Account Management</h3>{data.clusters.map(c=><div className="mini" key={c.id}><Card person={c} onEdit={edit}/></div>)}</section><section><Card person={data.designLead} onEdit={edit}/><h3>Design Leads</h3>{data.design.map(t=><div className="mini" key={t.lead.id}><Card person={t.lead} onEdit={edit}/><div className="people">{t.people.map(x=><Card key={x.id} person={x} onEdit={edit}/>)}</div></div>)}</section><section><Card person={data.contentLead} onEdit={edit}/><h3>Content Leads</h3>{data.content.map(t=><div className="mini" key={t.lead.id}><Card person={t.lead} onEdit={edit}/><div className="people">{t.people.map(x=><Card key={x.id} person={x} onEdit={edit}/>)}</div></div>)}</section></div>
  <div className="coverage"><div className="coverageHead"><h2>Account Coverage View · BU1</h2><p>Each account has its own Account Manager, Designer and Content Writer. Click any account card to edit the mapping.</p></div><div className="accountGrid">{data.accounts.map(a=><button className="accountCard" key={a.id} onClick={()=>setAccount({...a})}><strong>{a.name}</strong><span>{a.cluster}</span><div><b>Account Manager</b>{a.am}</div><div><b>Designer</b>{a.designer}</div><div><b>Content Writer</b>{a.writer}</div></button>)}</div></div>
 </div></section>
 {selected&&<div className="modal"><div className="dialog"><h2>Edit person</h2><label>Name<input autoFocus value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>Designation<input value={selected.designation} onChange={e=>setSelected({...selected,designation:e.target.value})}/></label><div className="actions"><button onClick={()=>setSelected(null)}>Cancel</button><button className="save" onClick={save}>Save</button></div></div></div>}
 {account&&<div className="modal"><div className="dialog"><h2>Edit account coverage</h2><label>Account / Brand<input autoFocus value={account.name} onChange={e=>updateAccount("name",e.target.value)}/></label><label>Cluster<input value={account.cluster} onChange={e=>updateAccount("cluster",e.target.value)}/></label><label>Account Manager<input value={account.am} onChange={e=>updateAccount("am",e.target.value)}/></label><label>Designer<input value={account.designer} onChange={e=>updateAccount("designer",e.target.value)}/></label><label>Content Writer<input value={account.writer} onChange={e=>updateAccount("writer",e.target.value)}/></label><div className="actions"><button onClick={()=>setAccount(null)}>Done</button></div></div></div>}
 </main>
}