"use client"
import { useEffect, useState } from "react"

type Person={id:string;name:string;designation:string}
type BU={id:string;name:string;head:Person;cde:Person;design:Person;clusters:Person[];accounts:Person[];designers:Person[]}
const p=(id:string,name:string,designation=""):Person=>({id,name,designation})
const seed={founders:p("founders","Founders"),finance:[p("finance-1","Finance 1"),p("finance-2","Finance 2"),p("finance-3","Finance 3")],mahima:p("mahima","Mahima","CBO"),ops:p("ops","Operations"),hr:p("hr","HR"),advisory:p("advisory","Advisory"),bus:[1,2,3,4].map(i=>({id:`bu${i}`,name:`Business Unit ${i}`,head:p(`bu${i}-head`,`BU Head`),cde:p(`bu${i}-cde`,`CDE`),design:p(`bu${i}-design`,`Design Series Director`),clusters:[],accounts:[],designers:[]})) as BU[]}
function Card({person,onEdit}:{person:Person;onEdit:(p:Person)=>void}){return <button className="card" onClick={()=>onEdit(person)}><strong>{person.name||"Name"}</strong>{person.designation&&<span>{person.designation}</span>}</button>}
export default function Home(){
 const [data,setData]=useState(seed);const [selected,setSelected]=useState<Person|null>(null)
 useEffect(()=>{const raw=localStorage.getItem("zen-org");if(raw)try{setData(JSON.parse(raw))}catch{}},[])
 useEffect(()=>{localStorage.setItem("zen-org",JSON.stringify(data))},[data])
 const edit=(x:Person)=>setSelected({...x})
 const save=()=>{if(!selected)return;const r=(x:Person)=>x.id===selected.id?selected:x;setData(d=>({...d,founders:r(d.founders),finance:d.finance.map(r),mahima:r(d.mahima),ops:r(d.ops),hr:r(d.hr),advisory:r(d.advisory),bus:d.bus.map(b=>({...b,head:r(b.head),cde:r(b.cde),design:r(b.design),clusters:b.clusters.map(r),accounts:b.accounts.map(r),designers:b.designers.map(r)}))}));setSelected(null)}
 const add=(id:string,key:"clusters"|"accounts"|"designers")=>setData(d=>({...d,bus:d.bus.map(b=>b.id===id?{...b,[key]:[...b[key],p(`${id}-${key}-${Date.now()}`,key==="clusters"?"Cluster Lead":key==="accounts"?"Account Manager":"Designer")]}:b)}))
 return <main><header><div><h1>Zen-Sheet</h1><p>Organization Builder</p></div><button className="reset" onClick={()=>{localStorage.removeItem("zen-org");location.reload()}}>Reset</button></header><section className="canvas"><div className="founder"><Card person={data.founders} onEdit={edit}/></div><div className="founderChildren"><div className="branch"><h3>Finance</h3>{data.finance.map(x=><Card key={x.id} person={x} onEdit={edit}/>)}</div><div className="branch mahima"><Card person={data.mahima} onEdit={edit}/><div className="sameLevel"><Card person={data.ops} onEdit={edit}/><Card person={data.hr} onEdit={edit}/><Card person={data.advisory} onEdit={edit}/>{data.bus.map(b=><div className="bu" key={b.id}><h2>{b.name}</h2><div className="leaders"><div><Card person={b.head} onEdit={edit}/><h4>BU Head</h4>{b.clusters.map(x=><Card key={x.id} person={x} onEdit={edit}/>)}{b.accounts.map(x=><Card key={x.id} person={x} onEdit={edit}/>)}<button onClick={()=>add(b.id,"clusters")}>+ Cluster Lead</button><button onClick={()=>add(b.id,"accounts")}>+ Account Manager</button></div><div><Card person={b.cde} onEdit={edit}/><h4>CDE</h4></div><div><Card person={b.design} onEdit={edit}/><h4>Design</h4>{b.designers.map(x=><Card key={x.id} person={x} onEdit={edit}/>)}<button onClick={()=>add(b.id,"designers")}>+ Designer</button></div></div></div>)}</div></div></div></section>{selected&&<div className="modal"><div className="dialog"><h2>Edit person</h2><label>Name<input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>Designation<input value={selected.designation} onChange={e=>setSelected({...selected,designation:e.target.value})}/></label><div className="actions"><button onClick={()=>setSelected(null)}>Cancel</button><button className="save" onClick={save}>Save</button></div></div></div>}</main>
}